package com.capgemini.airlinereservationsystemangularfinal;

import org.springframework.security.web.context.AbstractSecurityWebApplicationInitializer;

public class AirlineManagmentSystemSecurityApplicationInitializer extends
AbstractSecurityWebApplicationInitializer {

}
